name: CMake

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

env:
  BUILD_TYPE: Release
  CMAKE_INSTALL_PREFIX: inst

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.81.0
        libraries: filesystem
        
    - name: Setup macos dependencies
      if: runner.os == 'macOS'
      run: brew install libpng
      shell: bash
      
    - name: Setup windows dependencies
      if: runner.os == 'Windows'
      run: echo Hello
      shell: cmd

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.CMAKE_INSTALL_PREFIX}} -D "BOOST_ROOT=${{ steps.boost.outputs.root }}" -D "BOOST_LIBRARYDIR=${{ steps.boost.outputs.librarydir }}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target install

#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: build/inst/bin/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
