name: CMake

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_INSTALL_PREFIX: inst

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.81.0
        libraries: filesystem

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D "BOOST_ROOT=${{ steps.boost.outputs.root }}" -D "BOOST_LIBRARYDIR=${{ steps.boost.outputs.librarydir }}"

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target install
      
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: ${{ github.workspace }}/build/inst/bin
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
